---
# https://raw.githubusercontent.com/rubocop/rubocop/master/config/default.yml
AllCops:
  TargetRubyVersion: 2.6
  NewCops: disable
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false


Layout/IndentationStyle:
  Enabled: true
  EnforcedStyle: spaces

Layout/IndentationWidth:
  Enabled: true
  Width: 4
