---
# https://raw.githubusercontent.com/rubocop/rubocop/master/config/default.yml
AllCops:
  TargetRubyVersion: 2.6
  NewCops: disable
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 30

Metrics/AbcSize:
  Enabled: true
  Max: 28

Layout/IndentationStyle:
  Enabled: true
  EnforcedStyle: spaces

Layout/IndentationWidth:
  Enabled: true
  Width: 4

Style/MethodDefParentheses:
  Enabled: true
  EnforcedStyle: require_no_parentheses_except_multiline
